### ISSUE TITLE
Help Using this plugin

### ISSUE THREAD

**Issue by PortalGuy** [TenthGeek/ionic-snippets-sublime-plugin#5]
Hello,
This is not a issue, Need to ask this question:
It would be great if you have a help section on how to use this plugin.
A sample will greatly help.
Thanks
PortalGuy

**Comment by mbaljeetsingh** [comment]
After installing the plugin in the sublime text, you just need to write the **snippet code** and press **tab**. The complete code will appear.

e.g. Type **ion-bar-light** and press **tab**

See the [readme ](https://github.com/TenthGeek/ionic-snippets-sublime-plugin/blob/master/README.md)for more details.
